### PR TITLE
Reset SIGPIPE handler on https_close

### PR DESCRIPTION
**Pull request by andrewsoutar**
## Issue
`https_init` sets the `SIGPIPE` handler to `SIG_IGN` without resetting it. This is inherited by `login_duo`'s child process (signal _handlers_ aren't inherited by child processes, but signal _dispositions_ are), leading to (in my case) strange problems with shell pipelines. I would imagine it would also cause problems for `pam_duo`, but I haven't tested that.

## Summary of the change
The handler is now established in `https_init`; the old handler is saved in the `https_request` and reset on `https_close`.

## Test Plan
Without patch, you can see that the ignored SIGPIPE is propagated to the child process:
```bash
$ login_duo -f asoutar grep SigIgn /proc/self/status
Autopushing login request to phone...
Success. Logging you in...
SigIgn:	0000000000001000
```
After patch, you can see that there are no longer ignored signals in the child:
```
$ login_duo -f asoutar grep SigIgn /proc/self/status
Autopushing login request to phone...
Success. Logging you in...
SigIgn:	0000000000000000
```

### CODE REVIEW

**Comment by mbish** [comment]
Thanks for bringing this to our attention.
After looking into this: this bug specifically affects instances of `login_duo` with a user specified (via `-f`) it doesn't appear to affect `pam_duo`.

**Comment by mbish** [comment]
This change looks good to me. Could you add automated testing to this PR? Not all platforms have `/proc/self` so making a subprocess and issuing `SIGPIPE` to see that it's respected might be the most portable solution.

**Comment by mbish** [comment]
Sorry for the delay on this PR. I appreciate the work you've put into this but there's been a snag getting this change to work correctly with our internal CI. We haven't forgotten about this though and I'm hoping to have this as part of the next release.

**Comment by andrewsoutar** [comment]
Those changes all sound fine to me

**Comment by mbish** [comment]
This PR is now superseded by #231

**Pull request closed without merging**
