### PR TITLE
GECOS delimiter and position may be configured

### PR DESCRIPTION
**Pull request by agy**
Allow the GECOS delimiter and position to be configured in the config
file. Defaults to the previous values of "/" and 5 respectively.

Fail if the user has configured the delimiter character as ":" since
this is the default delimiter for /etc/passwd.

Example Usage 1:
```
    # Use GECOS field with default delimiter and position
    # username:x:0:0:code1/code2/code3//textField/usergecosparsed:/username:/bin/bash
    gecos_parsed = true
```

Example Usage 2:
```
    # Use GECOS field and set the delimiter and position
    # username:x:0:0:code1,usergecosparsed:/username:/bin/bash
    gecos_parsed = true
    gecos_delim = ,
    gecos_pos = 1
```

### CODE REVIEW

**Comment by mschwager** [comment]
Hey @agy!

Thanks for opening this PR! We'll include it in our roadmap and start looking at it as soon as possible!

**Comment by agy** [comment]
Related: https://github.com/duosecurity/duo_unix/pull/133

**Comment by xdesai** [comment]
Hi @agy!
Thanks for providing the PR for us to base some of this work off of! It appears you've allowed maintainers to add commits to your fork. I have a few edits I need to make to add test coverage and make a couple bug fixes. I just wanted to give you a heads up that I'm going to start pushing those to your fork in a little bit and then we'll go ahead and merge this in.
Thanks for helping contribute to Duo!

**Comment by agy** [comment]
@xdesai I believe that I have these permissions set already. Please let me know if it still does not work?

**Comment by xdesai** [comment]
Okay after thrashing around for a while I've finally figured out how to work with committing to a PR branch. I apologize for all the nasty merge commits on your fork I think I have a good idea how to do this in the future that will prevent that from happening. Thanks for being my guinea pig.
Tests have passed so I'm gonna go ahead and merge this in!
Thanks again for you work!

**Pull request merged**
