### PR TITLE
Add SNI support to API calls

### PR DESCRIPTION
**Pull request by skemper**
We need the client to send SNI so our traffic filtering can let it through.  This code and the existing tests worked for us (Ubuntu 14.04), but I don't know all your target devices.  If there's a list of platforms I should also verify on, please let me know.

### CODE REVIEW

**Comment by mschwager** [comment]
Thanks for the PR!

We actually have a pretty extensive list of platforms we support, they can be found in the first paragraph [here](https://duo.com/docs/duounix).

Rather than testing this functionality on all platforms we could wrap it in an `ifdef` guard and check for the existence of `SSL_set_tlsext_host_name` in `configure.ac`. Something like [this](https://github.com/duosecurity/duo_unix/blob/master/configure.ac#L170) should work.

**Comment by skemper** [comment]
In testing, I confirmed that this will fail to compile on CentOS 5, because that OS only comes with OpenSSL 0.9.8e.  SNI support was released as part of OpenSSL 0.9.8f :( looks like guards it is.  I'll work on that and update the PR.

**Comment by skemper** [comment]
Turns out the OpenSSL "function" is actually a macro, so we just check to see if that's defined or not.  The [Vagrantfile](https://gist.github.com/skemper/21018e69bf539ebaf5bb40446cc3b13e) I used for testing may be of some interest, though the tests currently fail on CentOS 5 for reasons I don't understand.  They're not SNI-related, though, so I can't really spend time tracking them down, sorry.

**Comment by mschwager** [comment]
Hmm, the tests pass for me on CentOS 5, but I have a different testing environment. Regardless, can we squash this into 1 commit? After that we're good to go!

**Comment by akgood** [comment]
It might be slightly cleaner to `#ifdef SSL_CTRL_SET_TLSEXT_HOSTNAME` - at least, that seems to be the way others have done this? But, whatever works, I guess.

**Comment by skemper** [comment]
OK, guard changed and commits squashed.  I was curious why other projects check the SSL_CTRL_SET_TLSEXT_HOSTNAME.  Since that's [the constant that actually indicates the SNI extension](https://github.com/openssl/openssl/blob/master/include/openssl/ssl.h), my best guess is that it's more "correct" to check for that than a macro which simply uses the constant.

**Comment by mschwager** [comment]
Excellent! Thanks again!

**Pull request merged**
