### PR TITLE
Significantly overhaul SELinux support.

### PR DESCRIPTION
**Pull request by qralston**
Specifically:

Move authlogin_duo.te from the pam_duo subdirectory to a separate selinux subdirectory. Conditionally add the selinux subdirectory to SUBDIRS in the top-level Makefile.am, depending on whether configure finds the prerequisite SELinux development tools installed on the system. If configure finds the tools, use them to build the module.

Rewrite the authlogin_duo policy module to use SELinux tunable policies to fine-tune SELinux behavior.

Using SELinux tunable policies (i.e., booleans) permits the system administrator to adjust the SELinux policy to match the precise configuration of Duo on the system. This is a better approach than having the authlogin_duo policy module blindly grant every possible SELinux type that could possibly use Duo authentication the ability to make outbound TCP connections.

The two initial tunable policies are pam_duo_permit_sshd and pam_duo_permit_local_login, which control whether the sshd_t and local_login_t types (respectively) can make outbound TCP connections to ports with the http_port_t or http_cache_port_t label.

Additional tunable policies can be created as needed (e.g., pam_duo_permit_xdm).

### CODE REVIEW

**Comment by qralston** [comment]
The motivation for this change:

We are configuring our systems to use Duo to protect all login points to our systems. That includes remote logins via ssh, local logins on a tty, and local graphical logins (via gdm).

The current authlogin_duo SELinux policy only adds a policy to permit logins via ssh. Specifically, it only adds permissions for the `ssh_t` type. All other types are denied.

Initially, I was going to update the policy to just permit the additional types we needed. But customizing the policy for _our_ specific environment isn't a good solution.

The real solution here is to build tunables into the policy so that the exact types permitted can be fine-tuned by the local system administrator, to grant only the SELinux types that are configured to use pam_duo.so in their respective PAM stacks the necessary permissions.

Since making this change necessitates using the full SELinux development tools to build the module, I took the opportunity to make the authlogin_duo module a full-fledged part of the build system, instead of an unloved stepchild hidden away in the pam_duo subdirectory.

This pull request works on Fedora and Red Hat Enterprise Linux 5/6/7. It _may_ work on other distributions, but I can't easily test that.

Questions? Comments? Other feedback?

**Comment by qralston** [comment]
@xdesai, what are your initial thoughts on this pull request? Do you have any concerns you'd like me to address?

We need a solution locally, so I'm going to move forward with our own duo_unix builds with this pull request committed. But I'd like to see this committed to upstream, so we don't have to maintain our own fork.

**Comment by xdesai** [comment]
Hey James! Sorry for the delay in response to this. Just finished doing a quick look over of the changes. Overall it does seem like this is taking things in the right direction for the SELinux module.
I wanted to set some expectations that I don't know how quickly we'll be able to validate and merge all of these changes. We'll do our best, but this isn't as high of a priority right now. These changes also will require changing the current workflow to install SELinux so that needs to be done with extra care and attention.

With that out of the way . Couple technical questions for you:
1. This requires a manual install still? `make -C selinux semodule-activate`?
2. You added configure checks for a bunch of tooling in order to use selinux, but a lot of that tooling got removed in your new Makefile. Does this get handled in `/usr/share/selinux/devel/Makefile`. For example `checkmodule`
3. I'm not familiar with tunable policies. After looking at your code changes I still don't understand how someone would turn these policies on. Can you point me in the right direction for this?

**Comment by qralston** [comment]
> I wanted to set some expectations that I don't know how quickly we'll be able to validate and merge all of these changes. We'll do our best, but this isn't as high of a priority right now.

Understood, and no worries—we just wanted some preliminary feedback to reassure us that the direction we chose wasn't something you were completely opposed to (e.g., because you already had plans to enhance the SELinux support in a different way).

> This requires a manual install still? `make -C selinux semodule-activate`?

Nope. If SELinux support is detected by configure, running `make` builds `authlogin_duo.pp`, and running `make install` installs the module. Running `make uninstall` will remove it.

Note that the `semodule-activate` and `semodule-deactivate` targets exist in the selinux subdirectory (moved from `pam_duo/Makefile.am`), but they have to be invoked manually; they aren't called as part of `make install` or `make uninstall`.

> You added configure checks for a bunch of tooling in order to use selinux, but a lot of that tooling got removed in your new Makefile. Does this get handled in `/usr/share/selinux/devel/Makefile`. For example `checkmodule`

Correct. The tooling that `configure.ac` looks for is required by `/usr/share/selinux/devel/Makefile`, which contributes all of the necessary targets to build the module correctly.

> I'm not familiar with tunable policies. After looking at your code changes I still don't understand how someone would turn these policies on. Can you point me in the right direction for this?

The tunables are expressed as SELinux booleans that the system administrator can toggle.

Example:

```
$ getsebool -a | grep pam_duo || echo no matches
no matches

$ rpm -Uvh duo_unix-1.10.3-1.el7.x86_64.rpm 
Preparing...                          ################################# [100%]
Updating / installing...
   1:duo_unix-1.10.3-1.el7            ################################# [100%]

$ getsebool -a | grep pam_duo || echo no matches
pam_duo_permit_local_login --> off
pam_duo_permit_sshd --> off

$ setsebool -P pam_duo_permit_sshd on

$ getsebool -a | grep pam_duo || echo no matches
pam_duo_permit_local_login --> off
pam_duo_permit_sshd --> on

$ rpm -e duo_unix

$ getsebool -a | grep pam_duo || echo no matches
no matches
```

See [booleans(8)](https://www.linux.org/docs/man8/booleans.html) for more information.

Any other questions for now?

**Comment by xdesai** [comment]
Thanks for the thorough answers to my questions!

> we just wanted some preliminary feedback to reassure us that the direction we chose wasn't something you were completely opposed to

As far as I know of our plans right now this approach definitely doesn't conflict with anything we were planning to do and hopefully it's something we can eventually get on the master.

This approach is looking pretty clean. I like that the make and install doesn't require any extra steps for SELinux but that you do have to toggle the switch to turn it on.

**Comment by qralston** [comment]
Hi @xdesai,

> This approach is looking pretty clean. I like that the make and install doesn't require any extra steps for SELinux but that you do have to toggle the switch to turn it on.

That's not actually how the patch works, though. With the patch applied, if the programs/files necessary to enable SELinux support are present on the system at build time, then it will build with SELinux support; otherwise it won't.

An alternative approach would be to make building with SELinux support conditional on a configure option (e.g., `--with-selinux`), and have the build fail if SELinux support is requested but the necessary programs/files aren't available. That would arguably be more predictable.

If you would prefer the `--with-selinux` approach, let me know, and I'll rework the merge request.

**Comment by xdesai** [comment]
Sorry I wasn't able to get back to you sooner on the approach of using --with-selinux.
I think allowing people to opt into new functionality is the best approach here. I like having our end users explicitly make a decision to whitelist Duo Unix in their selinux policies by passing in the flag.
I will bring this up again internally so we can reprioritize validating and merging in this work.

Thanks!

**Comment by qralston** [comment]
Hi @xdesai,

Understood. I think this pull request is now in the state that we both agree on: SELinux support isn't enabled unless `--with-selinux` is passed to `configure`.

Please let me know if your review encounters any issues. Thanks!

**Comment by qralston** [comment]
Also, just to clarify: even when `--with-selinux` is used, installing the resulting SELinux policy module won't change SELinux behavior _unless_ the system administrator explicitly sets the SELinux booleans to enabled it. This is deliberate, in order to prevent the installation of the pam_duo package from unexpectedly alternating effective SELinux protections. A permissive change to SELinux policy should always be opt-in; merely installing a package should not be inferred as implicit consent.

**Comment by qralston** [comment]
Upstream has changed significantly since I first submitted this pull request. I'm going to close this pull request, rebase, and resubmit.

**Pull request closed without merging**
