### PR TITLE
Adding configuration keyword ip_whitelist, this can list IP addresses fo...

### PR DESCRIPTION
**Pull request by paukstis**
...r which Duo authentication will be bypassed. When combined with logon script which would add whitelisted IP on first session, + cronjob which would remove whitelisted IPs when no more active sessions, this makes using Ansible on Duo enabled hosts easier.

### CODE REVIEW

**Comment by mschwager** [comment]
Hey! Just wanted to give you a heads up that we've seen your ticket and are currently evaluating it :)

Thanks for using Duo!

**Comment by mschwager** [comment]
Could this be accomplished with the Trusted networks feature?

2015-03-09-133317_1912x460_scrot

If you decide to use that feature it can also be scripted via integration modification (https://www.duosecurity.com/docs/adminapi#modify-integration) -> `ip_whitelist`

**Comment by paukstis** [comment]
Could be, but with my "Personal" type account I don't have access to API and this feature:
duosec-trustednetworks-conf
So I opted for "offline mode", patching duo_unix client.

**Comment by mschwager** [comment]
Ahh, I see! However, we encourage our users to use the Trusted Networks feature over an option like this so that authentication decisions are deferred to the Duo service as opposed to the application. This allows for more transparency and additional granularity in the logs. You are obviously welcome to continue to use your fork though! Have a good day :)

**Comment by jmdh** [comment]
I completely agree that in many cases centralising the whitelisting would be an appropriate choice, however aside from the free accounts not supporting this, this also means that there is no way to bypass the requirement when the network is offline. My use case is that my home network should both a) be trusted, so bypass 2FA, but also b) should not rely on my internet connection being up to be able to access my home ssh server when I'm on the local network.

Given these use cases, would you consider merging this or something like it? (I'd prefer that the whitelist used CIDR netblocks rather than just individual addresses, and I guess the patch may need updating anyway given it's a few years old.

**Pull request closed without merging**
