### PR TITLE
Add an RPM SPEC file for building on Red Hat Enterprise Linux (RHEL) and Fedora hosts.

### PR DESCRIPTION
**Pull request by qralston**
This pull request resolves issue #108 by adding an RPM spec file.

I have verified that this RPM spec file builds on RHEL5, RHEL6, RHEL7, and Fedora 27. It _may_ build on other RPM-based distributions, but I have not tested that.

### CODE REVIEW

**Comment by bensallen** [comment]
- Should this PR not also delete the old duo_unix.spec.in to avoid confusion?
- It would be great to see RPM building added into Travis. Travis being Ubuntu based, Mock or Docker would be needed.

Consider the following patch. The autotools patching is... pretty ugly. It seems slightly less ugly to bend the guidelines and skip having it around for versions that don't need it. %prep fails with `%setup -q -n %{name}-%{name}-%{version}`.

```
diff --git a/contrib/rhel/duo_unix.spec b/contrib/rhel/duo_unix.spec
index dae7056..1ba78d7 100644
--- a/contrib/rhel/duo_unix.spec
+++ b/contrib/rhel/duo_unix.spec
@@ -63,8 +63,8 @@ Group: Applications/System
 License: GPLv2
 URL: https://www.duo.com/
 Source0: https://github.com/duosecurity/duo_unix/archive/duo_unix-%{version}.tar.gz
-Patch0: duo_unix-1.10.2-include-autotools-files.patch
 %if 0%{?rhel} > 0 && 0%{?rhel} < 6
+Patch0: duo_unix-1.10.2-include-autotools-files.patch
 Buildroot: %(mktemp -ud %{_tmppath}/%{name}-%{version}-%{release}-XXXXXX)
 %endif

@@ -101,7 +101,7 @@ install this package.


 %prep
-%setup -q -n %{name}-%{name}-%{version}
+%setup -q -n %{name}-%{version}
 %if 0%{?rhel} > 0 && 0%{?rhel} < 7
 %patch0 -p1 -b .include-autotools-files
 %{__chmod} 0755 \
```

**Comment by qralston** [comment]
I agree about removing the old duo_unix.spec.in file—that's an oversight.

Ideally, the process that produces the distribution tar/ZIP files should create the autotooling required to build the package—requiring the packager to run autoreconf is almost always a bad idea, because it's frequently difficult to recreate the same autotooling chain that the developer is using.

But I'm not opposed to only including the autotooling patch on systems that actually need it (RHEL5 and RHEL6).

I can't reproduce your issue with %setup. Are you sure you are grabbing the exact same source tarball references in Source0? Because that tarball has the double prefix:

```
$ wget --quiet https://github.com/duosecurity/duo_unix/archive/duo_unix-1.10.2.tar.gz
$ tar tfz duo_unix-1.10.2.tar.gz | head -3
duo_unix-duo_unix-1.10.2/
duo_unix-duo_unix-1.10.2/.gitignore
duo_unix-duo_unix-1.10.2/.travis.yml
```

**Comment by bensallen** [comment]
> I can't reproduce your issue with %setup. Are you sure you are grabbing the exact same source tarball references in Source0?

Sorry missed this, I'm working directly from a git checkout of your branch.

```
make distclean && ./bootstrap && ./configure && make dist && rpmbuild -D "_sourcedir $PWD" -ba  contrib/rhel/duo_unix.spec
```

This is an odd directory structure for the archives. Can someone from Duo comment on why the Github releases are using ./duo_unix-duo_unix-<version> directory structures?

**Comment by qralston** [comment]
Any update on this?

**Comment by DuoKristina** [comment]
Thanks for your PR and all the work behind it. We'll review the suggested changes.

**Comment by xdesai** [comment]
Hey James,
Sorry for the radio silence on this. We're tracking this internally at the moment. I do appreciate you taking the time to do this work. We are discussing the merits of including the spec file in our repo at all and then we will try to review your PR.
In case you're curious here are a few of the pros/cons/questions we're weighing. If you care to include any thoughts as a member of the community please feel free.

Pros:
- Individuals who want to roll their own packages now can.
- It's open sourced with the rest of integration to allow people to make modifications that they need themselves.

Cons:
- We do not use this spec file so supporting it in our repo would be difficult.
- It may cause confusion because the spec file will not generate the same package as the one we provide and document the use of

Questions:
- Why do customers not want to use the packages that we build and provide?

**Comment by bensallen** [comment]
@xdesai 

> We do not use this spec file so supporting it in our repo would be difficult.

You could integrate RPM builds into the TravisCI tests. These would at least catch the high-level problems.

> Questions:
>    Why do customers not want to use the packages that we build and provide?

We need packages for aarch64, ppc64, and ppc64le for Duo to be successful inside our environment.

**Comment by bensallen** [comment]
> Questions:
> Why do customers not want to use the packages that we build and provide?

Another reason, Duo doesn't appear to release source RPMs on http://pkg.duosecurity.com/. Installing binaries that cannot be audited, even if we're trusting Duo to provide authentication services, is not desirable. Ideally the source RPMs should be released, and duo_unix ensured to have reproducible builds.

**Comment by qralston** [comment]
> Questions:
>
> * Why do customers not want to use the packages that we build and provide?

While we appreciate the fact that Duo provides RPM packages via a yum repository, the Duo-provided packages have some issues, as I describe in issue #110.

If duo_unix packages provided at http://pkg.duosecurity.com/ were to incorporate the improvements I suggested in issue #110, we would probably cease building local packages from source and just use the upstream packages.

**Comment by xdesai** [comment]
Ah that's right. I had forgotten you created that issue when I made that comment. Thanks for that and I'll make sure we include those suggestions in our discussion!

**Comment by qralston** [comment]
> Cons:
> 
> * We do not use this spec file so supporting it in our repo would be difficult.

I understand that it might make you feel a little queasy to have files in the distribution that you don't/can't 100% support.

However, this is largely the way that good open source software works. This is specifically why I put the spec file in a `contrib` subdirectory: doing so is an implicit disclaimer along the lines of "hey, we're provided the files in here in case they might be useful to others, but they were contributed (and are maintained) by others, not us, so we can't really offer support for the items here."

If it makes you feel better, put a `README` file in the `contrib` subdirectory that states exactly that.

Again, I appreciate that contemplating this might be unsettling. (This certainly isn't the way the Windows world works, for example.) But it's the way the Linux world works.

> * It may cause confusion because the spec file will not generate the same package as the one we provide and document the use of

Perhaps. But if you were to incorporate at least some of the suggestions in issue #110, the differences would be none to negligible.

(The only real differences that end users would notice are the first two suggestions: splitting the development files into a separate `-devel` subpackage, and renaming and/or relocating the `*.h` files so that they don't conflict with other packages.)

**Comment by xdesai** [comment]
Hey all,
We've talked over this issue internally and have come to a decision on what to do with the RPM spec file hosted in this repository. At this time we are not able to support a spec file for Duo Unix. We plan to reevaluate this in the future, but it's not on our roadmap at this time. I understand this is not the answer you wanted to hear, but I do encourage you submit feature requests so that our product team can properly assess desire for this feature and prioritize it accordingly. I would also ask that, if you are willing, please create a fork of Duo Unix that contains this spec file so other people can have a good starting point to work from.
I will keep this PR and your related issue open so that others can see this as an open request.

Thank you so much for using Duo and again I apologize for any difficulty this decision causes you.
-Xander

**Comment by qralston** [comment]
That's fine, @xdesai. I will maintain my separate fork with the spec file; others are welcome to help improve it.

Again, though, if you were to incorporate at least some of the suggestions in issue #110, we would be willing to use the packages you maintain at pkg.duosecurity.com.

**Comment by AaronAtDuo** [comment]
Closing, inactive for five years

**Pull request closed without merging**
